services:
  - type: web
    env: node
    name: prod-backend1
    repo: https://github.com/Shrinidhi1/express-hello-world.git
    buildFilter:
      paths:
        - apps/backend/**
    buildCommand: yarn && yarn build --filter=backend
    startCommand: cd apps/backend; yarn start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prod-db1
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: prod-redis1
          type: redis
          property: connectionString

  - type: web
    env: static
    name: prod-frontend1
    repo: https://github.com/Shrinidhi1/express-hello-world.git
    buildFilter:
      paths:
        - apps/frontend/**
    buildCommand: yarn && yarn build --filter=frontend
    staticPublishPath: ./apps/frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_GRAPHQL_HOST
        fromService:
          name: prod-backend1
          type: web
          property: host

  - type: redis
    name: prod-redis1
    ipAllowList: []

databases:
  - name: prod-db1
